#!/bin/bash

# Exit on any failure
set -e

# Check for uninitialized variables
set -o nounset

ctrlc() {
	killall -9 python
	mn -c
	exit
}

trap ctrlc SIGINT

start=`date`
exptid=`date +%b%d-%H:%M`

rootdir=buffersizing-$exptid
plotpath=util
iperf=~/iperf-patched/src/iperf

iface=s0-eth1

#only one run by default; the graph in the report was generated by
#averaging the results over 5 runs
#for run in 1 2 3 4 5; do
for run in 1; do
# 0 means only one flow
for flows_per_host in 0 1 2 5 10 50 100 200 300 400; do
#for flows_per_host in 0 1 2 5; do
	dir=$rootdir/nf$flows_per_host-r$run-regular

	python buffersizing.py --bw-host 1000 \
		--bw-net 62.5 \
		--delay 43.5 \
		--dir $dir \
		--nflows $flows_per_host \
		-n 3 \
		--iperf $iperf --cong reno # --fast --cong reno

	dir=$rootdir/nf$flows_per_host-r$run-paced

	python buffersizing.py --mod --bw-host 1000 \
                --bw-net 62.5 \
                --delay 43.5 \
                --dir $dir \
                --nflows $flows_per_host \
                -n 3 \
                --iperf $iperf --cong reno #--fast --cong reno

done
done

cat $rootdir/*/result.txt | sort -n -k 1
python plot-results.py --dir $rootdir -o $rootdir/result.png
echo "Started at" $start
echo "Ended at" `date`
